  datasource:
    url: jdbc:mysql://localhost:3306/appdb?useSSL=false&serverTimezone=UTC
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # lub none
    show-sql: false

  security:
    user:
      name: admin
      password: strongProdPassword
