spring:
  application:
    name: backend
  profiles:
    active: dev

server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: framework

devtools:
  restart:
    enabled: true

cors:
  allowed-origins:
    - http://localhost:3000
    - http://example.com

ratelimiter:
  requests: 50
  durationMinutes: 1
  logFrequency: 10

logging:
  level:
    root: INFO
    com.app.backend: DEBUG
  spring:
    output:
      ansi:
        enabled: ALWAYS
